# Generated by Django 4.1.13 on 2024-04-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bonus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MascotaAconseguida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicknameUsuari', models.CharField(max_length=50)),
                ('nivell', models.IntegerField(default=1)),
                ('equipada', models.BooleanField(default=False)),
                ('nomMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pets.mascota')),
            ],
        ),
    ]
