# Generated by Django 4.1.13 on 2024-04-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0002_mascota_img1_mascota_img1l_mascota_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='bonus',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='name',
            field=models.TextField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
