# Generated by Django 4.1.13 on 2024-04-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatLng',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BikeLanes',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('latLng', models.ManyToManyField(to='BikeLanes.latlng')),
            ],
        ),
    ]
