# Generated by Django 4.1.13 on 2024-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rutes', '__first__'),
        ('BikeLanes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikelanes',
            name='latLng',
            field=models.ManyToManyField(to='Rutes.punts'),
        ),
    ]
