# Generated by Django 4.1.13 on 2024-04-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeLanes', '0002_alter_bikelanes_latlng'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatLng',
        ),
    ]
