# Generated by Django 4.1.13 on 2024-04-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeLanes', '0003_delete_latlng'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeLane',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LatLng',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bike_lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lat_lngs', to='BikeLanes.bikelane')),
            ],
        ),
        migrations.DeleteModel(
            name='BikeLanes',
        ),
    ]
