# Generated by Django 4.1.13 on 2024-03-19 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punts',
            fields=[
                ('PuntId', models.AutoField(primary_key=True, serialize=False)),
                ('PuntName', models.CharField(blank=True, max_length=50, null=True)),
                ('PuntLat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('PuntLong', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Rutes',
            fields=[
                ('RuteId', models.AutoField(primary_key=True, serialize=False)),
                ('RuteName', models.CharField(max_length=50)),
                ('RuteDistance', models.DecimalField(decimal_places=6, max_digits=9)),
                ('RuteTime', models.IntegerField()),
                ('RuteRating', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracio',
            fields=[
                ('ValoracioId', models.AutoField(primary_key=True, serialize=False)),
                ('Valoracio', models.IntegerField()),
                ('RuteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rutes.rutes')),
            ],
        ),
        migrations.CreateModel(
            name='PuntsIntermedis',
            fields=[
                ('PuntInterId', models.AutoField(primary_key=True, serialize=False)),
                ('PuntOrder', models.IntegerField()),
                ('PuntId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rutes.punts')),
                ('RuteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rutes.rutes')),
            ],
        ),
    ]
