# Generated by Django 4.1.13 on 2024-04-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rutes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('mechanical', models.IntegerField(default=0)),
                ('ebike', models.IntegerField(default=0)),
                ('num_docks_available', models.IntegerField(default=0)),
                ('PuntId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Rutes.punts')),
            ],
        ),
    ]
