# Generated by Django 4.1.13 on 2024-03-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('last_updated', models.IntegerField(default=0)),
                ('mechanical', models.IntegerField(default=0)),
                ('ebike', models.IntegerField(default=0)),
                ('num_docks_available', models.IntegerField(default=0)),
            ],
        ),
    ]
