name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.2]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    #- name: Run Tests
      #run: |
        #python manage.py test
    - name: Send Webhook
      run: |
        curl -X POST http://nattech.fib.upc.edu:40360/webhook || [[ $? -eq 56 ]]


# deploy:
#   needs: build
#   runs-on: ubuntu-latest
#
#   steps:
#     - name: SSH into the VM and pull the code
#       uses: appleboy/ssh-action@master
#       with:
#         host: nattech.fib.upc.edu
#         port: 22036
#         username: alumne
#         password: ${{ secrets.SSH_PASSWORD }}  # Recomiendo usar un secreto para la contraseña SSH
#         script: |
#           echo "${{ secrets.SSH_PASSWORD }}" | sudo -S sudo -i
#           cd /BikeJoyBack  # Reemplaza esto con la ruta real de tu proyecto
#           git pull     # Realiza el pull del código desde GitHub
#     - name: Restart Apache
#       uses: appleboy/ssh-action@master
#       with:
#         host: nattech.fib.upc.edu
#         port: 22036
#         username: alumne
#         password: ${{ secrets.SSH_PASSWORD }}  # Recomiendo usar un secreto para la contraseña SSH
#         script: |
#           echo "${{ secrets.SSH_PASSWORD }}" | sudo -S sudo -i
#           systemctl restart apache2  # Reinicia Apache
# hola